### ISSUE TITLE
Matrix Multiplication

### ISSUE THREAD

**Issue by anishcr** [ocaml-multicore/parallel-programming-in-multicore-ocaml#20]
In matrix multiplication,

can't we change the code

`res.(i).(j) <- res.(i).(j) + a.(i).(k) * b.(k).(j)`

to

`res.(i).(j) <- a.(i).(k) * b.(k).(j)`

**Comment by zbroyar** [comment]
No, we can't b/c in this case `res.(i).(j)` will contain the last product instead of sum of products.

**Comment by anishcr** [comment]
Thanks. I got the matrix multiplication wrong.
